default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: billinho_development

test:
  <<: *default
  database: billinho_test

production:
  <<: *default
  database: billinho_production
  username: billinho
  password: <%= ENV['BILLINHO_DATABASE_PASSWORD'] %>
