# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      #Setup Rails
      - name: Setup Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
      #Setup gems
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      #Install dependencies
      - name: Install dependencies
        run:
          bundle install
      # Add or replace any other lints here
      - name: Lint Ruby files
        run: bin/rubocop --parallel
        
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to heroku
      uses: jctaveras/heroku-deploy@v1.0.0
      with:
        docker_heroku_process_type: web
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "billinho-api"
        heroku_email: "emerson.b.f02@outlook.com" 
        dockerfile_path: 'docker-compose.yaml' 
        justlogin: true
    - name: "Login to heroku registry"
      run: heroku container:login
    - name: "Build and push to heroku registry"
      run: heroku container:push web --app billinho-api
    - name: "Releases the container"
      run: heroku container:release web --app billinho-api
    env:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    

